FROM golang:1.26.4-alpine AS dev
RUN apk --no-cache add ca-certificates curl && \
    go install github.com/air-verse/air@latest && \
    go install github.com/swaggo/swag/cmd/swag@latest
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
WORKDIR /app
COPY ./go.mod ./go.sum ./
RUN go mod download
EXPOSE 8000 3333
CMD ["air", "-c", ".air.toml"]
