version: 2
updates:
  - package-ecosystem: gomod
    directory: /service/backend
    schedule:
      interval: weekly
    groups:
      go-deps:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /service/frontend
    schedule:
      interval: weekly
    groups:
      npm-deps:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
